---
title: "dsRNA_soaking_timecourse_qc"
author: "niko.popitsch"
date: "09/2022"
documentclass: article
fontsize: 10pt
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 14
    fig_height: 10
    fig_caption: true
    df_print: paged
  pdf_document:
    fig_width: 12
    fig_height: 10
    fig_caption: true
params:
    data_file:
      value: "/Volumes/groups/ameres/Niko/projects/Ameres/nina/dsRNA_soaking_timecourse/results/data.rds"
    out_dir:
      value: "/Volumes/groups/ameres/Niko/projects/Ameres/nina/dsRNA_soaking_timecourse/results/analysis/"
---

<style type="text/css">
body, td {
   font-size: 10px;
}
code.r{
  font-size: 10px;
}
pre {
  font-size: 10px
}
div.blue pre { background-color:lightblue; }
div.blue pre.r { background-color:blue; }
</style>

# Init
```{r}
require(data.table)
require(dplyr)
require(tidyr)
require(ggplot2)
require(stringr)
require(cowplot)
require(readr)
require(testthat)
require(tidylog)
require(glue)
require(rtracklayer)
require(tximport)
require(DESeq2)
require(tibble)
require(broom)
require(grid)
require(gridExtra)
count=dplyr::count
select=dplyr::select

# load data from TSV. Supports gzipped files
load_table = function(dataF, append="", header=T, nrows=Inf, skip=0) {
  dataF = as.character(paste0(dataF, append))
  print(paste("Loading", dataF))
  if ( endsWith(dataF, ".gz") ) {
    return(fread(cmd=paste('gunzip -c', dataF), header=header, sep="\t", skip=skip, na.strings=c("na","NA",".", "None"), nrows=nrows))
  } else {
    return(fread(dataF, header=header, sep="\t", skip=skip, na.strings=c("na","NA",".", "None"), nrows=nrows))
  }
}

# multiple plots with single title
my_plot_grid = function(..., main=NULL) {
  plot_row=plot_grid(...)
  title <- ggdraw() + draw_label( main, fontface = 'bold', x = 0, hjust = 0 ) + theme(plot.margin = margin(0, 0, 0, 7))
  return (plot_grid(title, plot_row, ncol = 1, rel_heights = c(0.1, 1)))
}

#
# Draw correlations between two columns
#
plot_corr = function(data, a, b, c=1, s=NULL, labx=a, laby=b, main=paste0("Correlation between ", a, " and ", b), drawdiag=F, log=F, limits0=T, removeOutliers=F, testCorrelation=F, cor_y_pos=0.85, binhex=T, direct_labels=F, return_plot=F) {
  if (testCorrelation) {
    print(cor.test(data[[a]], data[[b]],use="complete.obs"))
  }
  fil = data[complete.cases(data %>% select(!!sym(a), !!sym(b))),]
  #main = paste0(main, ", [n=", nrow(fil), "]")
  
  # plot correlations
  thecor = grobTree(textGrob(paste("r_pearson = ", round(cor(fil[[a]], fil[[b]], use = "complete.obs"), 4), "\nr_spearman = ", round(cor(fil[[a]], fil[[b]], use = "complete.obs", method="spearman"), 4),"\nn =",nrow(fil)  ), x = 0.1, y = cor_y_pos, hjust = 0, gp = gpar(col = "red", fontsize = 7)))
  
  p=ggplot(data=fil, aes_string(x=paste0('`',a,'`'), y=paste0('`',b,'`'))) +  
    ggtitle(main) + 
    annotation_custom(thecor) + 
    xlab(labx) + ylab(laby) 

  if ( binhex ) {
    p = p + stat_binhex(bins=100) + scale_fill_gradientn("", colours = rev(rainbow(10, end = 4/6)))
  } else {
    p = p + geom_point(aes_string(col=c, shape=s)) 
    if ( ! direct_labels) {
      p = p + guides(col=guide_legend(title=c))
    } else {
      p = p + geom_label_repel(aes(label = sample),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
        theme(legend.position="none")
    }
  }

  if ( drawdiag ) {
    p = p + geom_abline(intercept = 0, slope = 1, col="black",linetype="dotted")
  }
  if (log) {
    p = p + scale_x_log10() + scale_y_log10() + xlab(paste0('log(',a,')')) + ylab(paste0('log(',b,')'))
  }
  if ( limits0 & ! log ) {
    p = p + expand_limits(x = 0, y = 0)
  }
  p = p + theme_classic(base_size = 8)
  return(p)
}
```

# Data
```{r}
d = readRDS(params$data_file)
```

## QC

```{r}

p1 = parsed_read_stats %>% 
  group_by(sample_name) %>% 
  filter(category=='read_count') %>% 
  left_join(sample_sheet %>% select(sample_name, raw_reads), by='sample_name') %>% 
  mutate(frac=value/raw_reads) %>% 
  ggplot(aes(key, frac, fill=key)) +
  geom_col() +
  scale_fill_manual( values = c( "pass"="darkgreen", "filtered"="red" ), guide = "none" ) +
  facet_wrap(sample_name~.) +
  ylim(0,1) + xlab("") + ylab("") +
  coord_flip() + 
  ggtitle("Filtering stats")

known_srbcs=sample_sheet %>% pull(sRBC)
p2 = parsed_read_stats %>% 
  filter(category=='srbc') %>% 
  left_join(sample_sheet %>% select(sample_name, sRBC, raw_reads), by='sample_name') %>% 
  group_by(sample_name) %>% 
  mutate(true_srbc=case_when(key==sRBC~'true',key %in% known_srbcs~'known', TRUE ~'other')) %>% 
  mutate(total=sum(value)) %>% 
  group_by(sample_name, true_srbc, total) %>% 
  summarise(share=sum(value)) %>% 
  ungroup() %>% 
  mutate(frac=share/total) %>% 
  ggplot(aes(true_srbc, frac, fill=true_srbc)) +
  geom_col() +
  scale_fill_manual( values = c( "true"="darkgreen", "other"="red" ), guide = "none" ) +
  facet_wrap(sample_name~.)+
  ylim(0,1) + xlab("") + ylab("") +
  coord_flip() + 
  ggtitle("Fraction of reads with true, known or unknown (other sequence) sRBC 5-mer")

p3 = fc_stats %>% 
  left_join(sample_sheet %>% select(sample_name, raw_reads), by='sample_name') %>% 
  filter(key %in% c('Assigned', 'Unassigned_NoFeatures')) %>% 
  group_by(sample_name) %>% mutate(total=sum(value)) %>% ungroup() %>% 
  mutate(frac=value/total) %>% 
  ggplot(aes(key,frac,fill=key)) +
  geom_col() +
  scale_fill_manual( values = c( "Assigned"="darkgreen", "Unassigned_NoFeatures"="red" ), guide = "none" ) +
  facet_wrap(sample_name~., scales = 'free_x') +
  ylim(0,1) + xlab("") + ylab("") +
  coord_flip() + 
  ggtitle("Fraction of mapped-reads assigned to pre_miRNA annotations")

p4 = fc_stats %>% 
  left_join(sample_sheet %>% select(sample_name, raw_reads), by='sample_name') %>% 
  filter(key %in% c('Assigned')) %>% 
  ggplot(aes(sample_name,value)) +
  geom_col() + xlab("") + ylab("") +
  coord_flip() + 
  ggtitle("Raw numbers of pre_miRNA assigned reads")

plot_grid(p1,p2,p3,p4, labels=c('A','B','C','D'))
```

### QC :: fraction of aligned reads

```{r}
p1 = fc %>% 
  filter(Feature_type=='miRNA_primary_transcript') %>% 
  group_by(sample_name, raw_reads, NaIO4_oxidized) %>% 
  summarise(miRNA_counts=sum(count)) %>% 
  ggplot(aes(sample_name, miRNA_counts, col=NaIO4_oxidized)) +
  geom_point() +
  coord_flip() +
  ggtitle("miRNA_read counts for miRNA_primary_transcript")



tab = fc_stats %>% 
  filter(key%in% c("Assigned","Unassigned_MultiMapping","Unassigned_NoFeatures" )) %>% 
  pivot_wider(names_from=key, values_from=value) %>% 
  left_join(
    parsed_read_stats %>% 
      filter(category=='read_count') %>% 
      select(-category) %>% 
      pivot_wider(names_from=key, values_from=value),
    by='sample_name'
  )


p2 = tab %>% mutate(
  mapped_reads=Assigned+Unassigned_MultiMapping+Unassigned_NoFeatures,
  unmapped_reads=pass-mapped_reads,
  raw_reads=pass+filtered,
  frac_filtered=filtered/raw_reads,
  frac_unmapped=unmapped_reads/raw_reads,
  frac_mapped=mapped_reads/raw_reads,
  ctrl=frac_filtered+frac_unmapped+frac_mapped) %>% 
  select(sample_name, filtered=frac_filtered, unmapped=frac_unmapped, mapped=frac_mapped) %>% 
  pivot_longer(-c(sample_name)) %>% 
  mutate(name=factor(name, levels=rev(c('mapped', 'unmapped', 'filtered')))) %>% 
  ggplot(aes(sample_name, value, fill=name)) +
  geom_col() +
  coord_flip() +
  ggtitle("Fraction of filtered/unmapped reads") +
  xlab("") + ylab("")

plot_grid(p1,p2)

```

### QC :: Normalization

```{r}

sc %>% filter(methylated=='yes') %>% 
  mutate(si_count_norm=si_counts/si_conc) %>% 
  group_by(sample_name) %>% 
  summarise(s_raw=sum(si_counts), s_norm=sum(si_count_norm)) %>% 
  pivot_longer(-c(sample_name)) %>% 
  ggplot(aes(sample_name, value, fill=name)) + geom_col() + 
  facet_grid(name~., scales = 'free') +
  ggtitle("Raw and normlized sum of counts for methylated spike-ins") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


## Spike-ins

spike-ins mX2, mX4, mX6, mX8 are 2'-O-methylated and thus are expected to be enriched in samples that are oxidized with NaIO4.
 
```{r}
p1 = sc %>% 
  ggplot(aes(si_conc, si_counts, col=sample_name, group=sample_name)) +
  geom_point() +
  geom_line() +
  #geom_smooth(method='lm',se = FALSE) +
  facet_wrap(paste0('methylated: ',methylated)~., scales = 'free_x')+
  scale_x_log10() +
  scale_y_log10() +
  ggtitle("Target concentrations vs read counts for spike-in sequences")

p2 = sc %>% 
  ggplot(aes(si_conc, si_counts, col=NaIO4_oxidized, group=sample_name)) +
  geom_point() +
  #geom_line() +
  geom_smooth(method='lm',se = FALSE) +
  facet_wrap(paste0('methylated: ',methylated)~., scales = 'free_x')+
  scale_x_log10() +
  scale_y_log10() +
  ggtitle("Target concentrations vs read counts for spike-in sequences",
          "Lines: linear regression")

p3 = sc %>% 
  filter(!is.na(si_name)) %>% 
  mutate(si_count_norm=si_counts/si_conc) %>% 
  group_by(sample_name,NaIO4_oxidized,methylated) %>% 
  summarise(si_count_norm_sum=sum(si_count_norm)) %>% 
  ggplot(aes(sample_name, si_count_norm_sum, fill=methylated)) +
  geom_col(position='dodge') +
  facet_wrap(paste0('Oxidized: ',NaIO4_oxidized)~., scales = 'free') +
  ggtitle("Sum of spikein read counts (norm by input concentration)") +
  coord_flip() + xlab("") + ylab("")

p4 = sc %>% 
  mutate(cat=case_when(
    is.na(si_name)~'miRNA read',
    TRUE~'spikein read'
    )) %>% group_by(sample_name, cat, NaIO4_oxidized) %>% 
  summarise(count=sum(si_counts)) %>% 
  ggplot(aes(sample_name, count, fill=cat)) +
  geom_col(position='dodge') +
  coord_flip() + xlab("") + ylab("") +
  ggtitle("Raw counts of spikein vs miRNA reads") 
  
  
plot_grid(p1,p2, p3, p4, labels=c('A','B','C','D'))
```

## Comparison of pipelines

```{r}
# load thomas data
th_miRNA_counts = 
  load_table(paste0(params$thomas_data, 'allProperties.miRNA.tf0.12.txt')) %>% 
  select(chr, p5, strand, gname, starts_with('align.GM.'), starts_with('align.PM.')) %>% 
  mutate(Name=tolower(paste0('dme-', str_remove(gname, 'RM-')))) %>% 
  pivot_longer(cols=starts_with('align.'), names_to = c('alignment_type', 'sample_id'), 
               values_to='read_count', names_pattern = "align.([^.]*).([^.]*)",) %>% 
  pivot_wider(names_from=alignment_type, values_from=read_count) %>% 
  mutate(read_counts=GM+PM) %>% 
  mutate(sample_id=as.numeric(sample_id))

tab = fc %>%
  filter(Feature_type=='miRNA') %>% 
  mutate(Name=tolower(Name)) %>% 
  left_join(th_miRNA_counts, by=c('sample_id', 'Name')) %>% 
  filter(!is.na(read_counts)) %>% 
  dplyr::rename(thomas_norm=read_counts,
         niko_raw=count) %>% 
  as_tibble()


p1 = tab %>% plot_corr('thomas_norm', 'niko_raw', 'sample_name', labx='thomas_norm (GM+PM)', laby='niko_raw', 
                  main='Correlation between miRNA counts for both pipelines', 
                  drawdiag=F, log=T, testCorrelation=T, cor_y_pos=0.85, binhex=T, direct_labels=F, return_plot=T)

p2 = tab %>% 
  ggplot(aes(thomas_norm, niko_raw, col=NaIO4_oxidized )) +
  geom_point() +
  facet_wrap(sample_name~.) +
  scale_x_log10() +
  scale_y_log10()

plot_grid(p1,p2)
```
