---
title: "analyze_test_mappers.Rmd"
author: "niko.popitsch"
date: "05/2023"
documentclass: article
fontsize: 10pt
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 14
    fig_height: 10
    fig_caption: true
    df_print: paged
  pdf_document:
    fig_width: 12
    fig_height: 10
    fig_caption: true
params:
    results_dir:
      value: "/Volumes/groups/ameres/Niko/projects/Ameres/srna_pipeline/mapper_test/results/"
---

<style type="text/css">
body, td {
   font-size: 10px;
}
code.r{
  font-size: 10px;
}
pre {
  font-size: 10px
}
div.blue pre { background-color:lightblue; }
div.blue pre.r { background-color:blue; }
</style>

# Init
```{r}
require(data.table)
require(dplyr)
require(tidyr)
require(ggplot2)
require(stringr)
require(cowplot)
require(readr)
require(testthat)
require(tidylog)
require(glue)
require(rtracklayer)
require(tximport)
require(DESeq2)
require(tibble)
library(broom)
require(ggpmisc)

count=dplyr::count
select=dplyr::select

# load data from TSV. Supports gzipped files
load_table = function(dataF, append="", header=T, nrows=Inf, skip=0, colClasses=NULL) {
  dataF = as.character(paste0(dataF, append))
  print(paste("Loading", dataF))
  if ( endsWith(dataF, ".gz") ) {
    return(fread(cmd=paste('gunzip -c', dataF), header=header, sep="\t", skip=skip, na.strings=c("na","NA",".", "None"), nrows=nrows, colClasses=colClasses))
  } else {
    return(fread(dataF, header=header, sep="\t", skip=skip, na.strings=c("na","NA",".", "None"), nrows=nrows,
                  colClasses=colClasses))
  }
}

# helper to plot a correlation
plot_corr=function(tab, a, b, c, s, al, main=paste0(deparse(substitute(a)), ' vs ', deparse(substitute(b))), col_scale=my_colors, alpha_scale=my_alpha, draw_legend=TRUE) {
  thecor=paste0( 'R_pear=',
    round( tab %>% ungroup() %>% select(x={{a}}, y={{b}}) %>% summarize(R=cor(x,y, use = "complete.obs", method="pearson")) %>% pull(R), 2),
    ', R_spear=',
    round( tab %>% ungroup() %>% select(x={{a}}, y={{b}}) %>% summarize(R=cor(x,y, use = "complete.obs", method="spearman")) %>% pull(R), 2)
  )
  p = tab %>% ggplot(aes({{a}}, {{b}}, col={{c}}, shape={{s}}, alpha={{al}})) + geom_point() +
    scale_x_log10() +
    scale_y_log10() +
    geom_abline(slope=1, intercept = 0, linetype='dotted') + 
    scale_color_manual(values = col_scale, limits = force) + 
    scale_alpha_manual(values = alpha_scale, limits = force)+
    ggtitle(main, thecor)
  if (!draw_legend) {
    p = p + theme(legend.position="none")
  }
  return(p)
}

# multiple plots with single title
my_plot_grid = function(..., main=NULL) {
  plot_row=plot_grid(...)
  title <- ggdraw() + draw_label( main, fontface = 'bold', x = 0, hjust = 0 ) + theme(plot.margin = margin(0, 0, 0, 7))
  return (plot_grid(title, plot_row, ncol = 1, rel_heights = c(0.1, 1)))
}

my_colors=c(
  "low"="grey",
  "medium"="goldenrod4",
  "high"="green4",
  "spikein_methylated"="red",
  "spikein_unmethylated"="black"
)
my_alpha=c(
  "miRNA"=0.25,
  "miRNA_primary_transcript"=0.25,
  "spikein"=1
)

```

# Data
```{r}
dataset=c('tailor', 'bowtie', 'hisat3n', 'ngm', 'srnaMapper')
d=list()
d[['stats']]=list()
d[['iso']]=list()
for (ds in dataset) {
  d[['stats']][[ds]] = load_table(paste0(params$results_dir, 'mapped_reads_',ds,'/224823_S18_L004_R1_001_trimmed.stats.tsv'))
  d[['iso']][[ds]] = load_table(paste0(params$results_dir, 'mapped_reads_',ds,'/224823_S18_L004_R1_001_trimmed.iso.tsv'))
}
d[['stats']]=d[['stats']] %>% bind_rows(.id='ds')
d[['iso']] =d[['iso']] %>% bind_rows(.id='ds')
d[['meta']]=load_table(paste0(params$results_dir, 'mapped_reads_tailor/224823_S18_L004_R1_001_trimmed.meta.tsv'))
```
# Correlations
```{r}

tab = d$iso %>% #filter(gene_id=='Mmu-Let-7-P1c_pre') %>% 
  group_by(ds, gene_id, type) %>% 
  summarise(reads_norm=sum(reads_norm)) %>% 
  pivot_wider(names_from=ds, values_from=reads_norm, id_cols=c('gene_id', 'type')) %>% 
  mutate_all(~replace(., is.na(.), 0))


plot_grid(
  
  my_plot_grid(
    tab %>% filter(type=='miRNA') %>% plot_corr(tailor, bowtie),
    tab %>% filter(type=='miRNA') %>% plot_corr(tailor, ngm),
    tab %>% filter(type=='miRNA') %>% plot_corr(tailor, srnaMapper),
    tab %>% filter(type=='miRNA') %>% plot_corr(tailor, hisat3n),
    main='miRNAs'
  ),
  my_plot_grid(
    tab %>% filter(type=='pre_miRNA') %>% plot_corr(tailor, bowtie),
    tab %>% filter(type=='pre_miRNA') %>% plot_corr(tailor, ngm),
    tab %>% filter(type=='pre_miRNA') %>% plot_corr(tailor, srnaMapper),
    tab %>% filter(type=='pre_miRNA') %>% plot_corr(tailor, hisat3n),
    main='pre_miRNA'
  )
)
  

```

# Differences
```{r}
tab %>% mutate(diff=abs(bowtie-tailor)) %>% ungroup() %>% slice_max(diff, n=10)
```